import { StyleSheet, Platform, Dimensions } from "react-native";

const { height } = Dimensions.get("screen");
const height_logo = height * 0.09;

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
  },
  globalContainer: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#C5CBE3",
  },
  titleText: {
    fontSize: 18,
    color: "#333",
  },
  textPage: {
    fontSize: 16,
    color: "#333",
    fontWeight: "bold",
    letterSpacing: 1,
    paddingLeft: 10,
  },
  cartHeader: {
    fontSize: 14,
    color: "#333",
    fontWeight: "bold",
    letterSpacing: 1,
    paddingLeft: 5,
    marginTop: 8,
    fontSize: 16
  },
  cartContent: {
    fontSize: 12,
    color: "#333",
    fontWeight: "bold",
    letterSpacing: 1,
    paddingLeft: 5,
    marginTop: 5,
  },
  input: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
    color: "#05375a",
  },
  inputTextArea: {
    margin: 12,
    borderWidth: 1,
    padding: 10,
    color: "#05375a",
  },
  textInput: {
    flex: 1,
    marginTop: Platform.OS === "ios" ? 0 : 5,
    paddingLeft: 10,
    color: "#05375a",
    borderBottomWidth: 1,
    height: 40,
    borderColor: "green",
  },
  gridView: {
    flex: 1,
  },
  itemContainer: {
    borderRadius: 3,
    padding: 10,
    height: 150,
  },
  itemName: {
    fontSize: 18,
    color: "#FFF",
    fontWeight: "bold",
  },
  itemCode: {
    fontWeight: "bold",
    fontSize: 14,
    marginTop: 5,
    color: "#333",
    letterSpacing: 1,
    paddingLeft: 5,
  },
  editbutton: {
    backgroundColor: "#FFBF00",
    height: 30,
    borderRadius: 3,
    width: 50,
    alignItems: "center",
    padding: 6,
  },
  deletebutton: {
    backgroundColor: "#FF7F50",
    height: 30,
    borderRadius: 3,
    width: 60,
    alignItems: "center",
    padding: 6,
  },
  buttenContainer: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    alignItems: "flex-end",
    justifyContent: "space-between",
    textAlign: "center",
  },
  addButton: {
    right: 20,
    alignItems: "flex-end",
  },
  dropDownItemStyle: {
    fontSize: 14,
    color: "#05375a",
  },
  dropDownPickerStyle: {
    height: 40,
    color: "#05375a",
    fontSize: 14,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
  text_comp: {
    marginTop: 30,
  },
  validation_text_msg: {
    color: "red",
    marginTop: 2,
    position: "absolute",
    justifyContent: "flex-end",
    flexDirection: "row",
    textAlign: "right",
  },
  submitButton: {
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderColor: "#009387",
    borderWidth: 1,
    backgroundColor: "#009387",
    marginTop: 15,
    margin: 12,
    padding: 10,
  },
  icon: {
    position: "absolute",
    left: 16,
  },
  iconStart: {
    left: 16,
  },
  iconEnd: {
    left: 16,
    alignItems: "flex-end",
  },

  header: {
    width: "100%",
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#009387",
  },
  headerText: {
    fontWeight: "bold",
    fontSize: 20,
    color: "#333",
    letterSpacing: 1,
    textAlign: "center",
    width: "100%",
  },
  serviceNameText: {
    right: 5,
    position: "absolute",
    justifyContent: "flex-end",
    flexDirection: "row",
    textAlign: "right",
    marginTop: 30,
  },
  serviceNameText2: {
    fontSize: 10,
    color: "#333",
    letterSpacing: 1,
    letterSpacing: 0,
    marginTop: 30,
  },
  cardMyRequest: {
    backgroundColor: "white",
    shadowOffset: { width: 1, height: 1 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 1,
    marginHorizontal: 1,
    marginTop:1,
  },
  cardControlMyRequestBody: {
    elevation: 2,
    backgroundColor: "white",
    shadowOffset: { width: 1, height: 1 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 1,
    marginHorizontal: 1,
    marginTop: 1,
  },
  cardControlBarMyRequest: {
    backgroundColor: "white",
    shadowOffset: { width: 1, height: 1 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 1,
    marginHorizontal: 1,
    height: 40,
  },
  cardProfile: {
    borderRadius: 0,
    elevation: 0,
    backgroundColor: "white",
    shadowOffset: { width: 1, height: 1 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 2,
    marginHorizontal: 2,
    marginVertical: 2,
  },
  cardConsent: {
    marginHorizontal: 10,
    marginVertical: 20,
  },
  logo: {
    width: height_logo,
    height: height_logo,
    borderColor: "black",
  },
  profileInput: {
    height: 30,
    margin: 1,
    borderWidth: 0.5,
    padding: 5,
    color: "#05375a",
    width: 200,
    marginLeft: 30,
  },
  signIn: {
    width: 150,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
    flexDirection: "row",
  },
  signupContainer: {
    flex: 1,
    backgroundColor: "#009387",
  },
  text_header: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 25,
    textAlign: "center",
  },
  footerSignUp: {
    // flex: Platform.OS === "ios" ? 3 : 5,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  text_footer: {
    color: "#05375a",
    fontSize: 16,
  },
  popup_text: {
    color: "#05375a",
    fontSize: 16,
    marginLeft: 92,
    marginBottom: 5,
    fontWeight: "bold",
  },
  action: {
    flexDirection: "row",
  },
  checkbox: {
    alignSelf: "center",
  },
  button: {
    alignItems: "center",
    marginTop: 20,
  },
  modalButton: {
    height: 35,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderColor: "#009387",
    borderWidth: 1,
    backgroundColor: "#009387",
    marginTop: 15,
    margin: 15,
    padding: 10,
    //width: 60,
  },
  modalCancelButton: {
    height: 35,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderColor: "indianred",
    borderWidth: 1,
    backgroundColor: "indianred",
    marginTop: 15,
    margin: 15,
    padding: 10,
    //width: 60,
  },
  cardControlBarDashboard: {
    borderBottomEndRadius: 6,
    borderBottomLeftRadius: 6,
    elevation: 2,
    backgroundColor: "white",
    shadowOffset: { width: 1, height: 1 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 2,
    marginHorizontal: 5,
    marginBottom: 3,
    marginTop: 1,
    height: 40,
  },
  cartFeedback: {
    elevation: 0,
    backgroundColor: "white",
    shadowOffset: { width: 1, height: 1 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 1,
    marginHorizontal: 1,
    marginRight:2,
    marginLeft:2
  },
  vehicleCard:{
    borderRadius: 2,
    borderBottomEndRadius: 0,
    borderBottomStartRadius: 0,
    elevation: 2,
    backgroundColor: "white",
    shadowOffset: { width: 1, height: 1 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 2,
    marginHorizontal: 2
  }
});
